# URL for API call
api:
  url: "http://localhost:11434/api/generate"
  headers:
    Content-Type: "application/json"
    User-Agent: "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.8) Gecko/20100722 Firefox/3.6.8 GTB7.1 (.NET CLR 3.5.30729)"
    Referer: "http://example.com"

# Model
model:
  name: "gemma2:9b-instruct-fp16"
  parameters:
    stream: false

# Prompt
test:
  prompt_file: "config/prompt-template-7.txt"
  num_trials: 10

# Performance
metrics:
  show_tokens_per_second: true
  show_token_count: true 
