# URL for API call
api:
  url: "http://143.215.144.51:11434/api/generate"
  headers:
    Content-Type: "application/json"

# Model
model:
  name: "llama3.2"
  parameters:
    stream: false

# Prompt
test:
  prompt: "What color is the sky?"

# Performance
metrics:
  show_tokens_per_second: true